language: r

r:
- oldrel
- release
os:
- linux
- osx

sudo: false
cache: packages

branches:
  only:
  - master
  - dev

after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'library(goodpractice);gp(checks=all_checks()[!grepl("(rcmdcheck|covr)",all_checks())])'
- Rscript -e 'devtools::spell_check()'

notifications:
  email:
    recipients:
      - ross@ecohealthalliance.org
    on_success: change
    on_failure: change
