# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
        if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) { cinst pandoc }
        $env:Path += ";C:\Program Files (x86)\Pandoc\"
        pandoc -v

install:
  ps: Bootstrap

cache:
  - C:\RLibrary
  - C:\Program Files (x86)\Pandoc\

# Adapt as necessary starting from here

environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    _R_CHECK_FORCE_SUGGESTS_: 0
    R_VERION: release
    GITHUB_PAT:
      secure: Qpu7QAryewNdbeyqNf6iwaE6F30R96SCNszl1ShoMkIb4BUf0Vnj2q2w1Wx2GGEJ
    EIDITH_GLOBAL_USERNAME:
      secure: ruGUJ3FjodOBxAE/viC9PQ==
    EIDITH_GLOBAL_PASSWORD:
      secure: GEKQgxGJhzyrYU7ZOOK3Gw==
    EIDITH_EHA_USERNAME:
      secure: 6oL8HHqf+Z4MCBxT74omcQ==
    EIDITH_EHA_PASSWORD:
      secure: UeDxVAm9i3SFc/ETVN+nLQ==
  matrix:
  - R_VERSION: oldrel
  - R_VERSION: release
  - R_VERSION: devel

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
  - provider: Email
    to:
      - ross@ecohealthalliance.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
